// Mapping strict pour les formulaires de demande (frontend), aligné sur les types backend
import {
  ServiceType,
  Gender,
  MaritalStatus,
  PassportType,
  VisaType,
  JustificationDocumentType,
  OriginCountryParentRelationshipType
} from "./demande-types";

export const DOCUMENTS = [
  {
    key: ServiceType.VISA,
    label: "Visa",
    fields: [
      { name: "personFirstName", label: "Prénom", type: "text", required: true },
      { name: "personLastName", label: "Nom", type: "text", required: true },
      { name: "personGender", label: "Genre", type: "select", required: true, options: Object.values(Gender) },
      { name: "personNationality", label: "Nationalité", type: "text", required: true },
      { name: "personBirthDate", label: "Date de naissance", type: "date", required: true },
      { name: "personBirthPlace", label: "Lieu de naissance", type: "text", required: true },
      { name: "personMaritalStatus", label: "État civil", type: "select", required: true, options: Object.values(MaritalStatus) },
      { name: "passportType", label: "Type de passeport", type: "select", required: true, options: Object.values(PassportType) },
      { name: "passportNumber", label: "Numéro de passeport", type: "text", required: true },
      { name: "passportIssuedBy", label: "Délivré par", type: "text", required: true },
      { name: "passportIssueDate", label: "Date de délivrance du passeport", type: "date", required: true },
      { name: "passportExpirationDate", label: "Expiration du passeport", type: "date", required: true },
      { name: "profession", label: "Profession", type: "text", required: false },
      { name: "employerAddress", label: "Adresse de l'employeur", type: "text", required: false },
      { name: "employerPhoneNumber", label: "Téléphone de l'employeur", type: "text", required: false },
      { name: "visaType", label: "Type de visa", type: "select", required: true, options: Object.values(VisaType) },
      { name: "durationMonths", label: "Durée (mois)", type: "number", required: true },
      { name: "destinationState", label: "Destination", type: "text", required: false },
      { name: "visaExpirationDate", label: "Expiration du visa", type: "date", required: false },
    ],
  },
  {
    key: ServiceType.LAISSEZ_PASSER,
    label: "Laissez-passer",
    fields: [
      { name: "personFirstName", label: "Prénom", type: "text", required: true },
      { name: "personLastName", label: "Nom", type: "text", required: true },
      { name: "personBirthDate", label: "Date de naissance", type: "date", required: true },
      { name: "personBirthPlace", label: "Lieu de naissance", type: "text", required: true },
      { name: "personProfession", label: "Profession", type: "text", required: false },
      { name: "personNationality", label: "Nationalité", type: "text", required: true },
      { name: "personDomicile", label: "Domicile", type: "text", required: false },
      { name: "fatherFullName", label: "Nom du père", type: "text", required: false },
      { name: "motherFullName", label: "Nom de la mère", type: "text", required: false },
      { name: "destination", label: "Destination", type: "text", required: false },
      { name: "travelReason", label: "Motif du voyage", type: "text", required: false },
      { name: "accompanied", label: "Accompagné ?", type: "checkbox", required: true },
      { name: "justificationDocumentType", label: "Type de justificatif", type: "select", required: false, options: Object.values(JustificationDocumentType) },
      { name: "justificationDocumentNumber", label: "Numéro du justificatif", type: "text", required: false },
      { name: "laissezPasserExpirationDate", label: "Expiration du laissez-passer", type: "date", required: true },
    ],
  },
  {
    key: ServiceType.POWER_OF_ATTORNEY,
    label: "Procuration",
    fields: [
      { name: "agentFirstName", label: "Prénom du mandataire", type: "text", required: true },
      { name: "agentLastName", label: "Nom du mandataire", type: "text", required: true },
      { name: "agentJustificationDocumentType", label: "Type de justificatif du mandataire", type: "select", required: false, options: Object.values(JustificationDocumentType) },
      { name: "agentIdDocumentNumber", label: "Numéro justificatif du mandataire", type: "text", required: false },
      { name: "agentAddress", label: "Adresse du mandataire", type: "text", required: false },
      { name: "principalFirstName", label: "Prénom du donneur d'ordre", type: "text", required: true },
      { name: "principalLastName", label: "Nom du donneur d'ordre", type: "text", required: true },
      { name: "principalJustificationDocumentType", label: "Type de justificatif du donneur d'ordre", type: "select", required: false, options: Object.values(JustificationDocumentType) },
      { name: "principalIdDocumentNumber", label: "Numéro justificatif du donneur d'ordre", type: "text", required: false },
      { name: "principalAddress", label: "Adresse du donneur d'ordre", type: "text", required: false },
      { name: "powerOfType", label: "Type de procuration", type: "text", required: false },
      { name: "reason", label: "Motif", type: "text", required: false },
    ],
  },
  {
    key: ServiceType.CONSULAR_CARD,
    label: "Document consulaire",
    fields: [
      { name: "personFirstName", label: "Prénom", type: "text", required: true },
      { name: "personLastName", label: "Nom", type: "text", required: true },
      { name: "personBirthDate", label: "Date de naissance", type: "date", required: true },
      { name: "personBirthPlace", label: "Lieu de naissance", type: "text", required: true },
      { name: "personProfession", label: "Profession", type: "text", required: false },
      { name: "personNationality", label: "Nationalité", type: "text", required: true },
      { name: "personDomicile", label: "Domicile", type: "text", required: false },
      { name: "personAddressInOriginCountry", label: "Adresse au pays d'origine", type: "text", required: false },
      { name: "fatherFullName", label: "Nom du père", type: "text", required: false },
      { name: "motherFullName", label: "Nom de la mère", type: "text", required: false },
      { name: "justificationDocumentType", label: "Type de justificatif", type: "select", required: false, options: Object.values(JustificationDocumentType) },
      { name: "justificationDocumentNumber", label: "Numéro du justificatif", type: "text", required: false },
      { name: "cardExpirationDate", label: "Expiration de la carte", type: "date", required: false },
    ],
  },
];
